version: '3.8'

services:
  nestjs:
  container_name: nestjs
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - '3000:3000'
  environment:
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USERNAME=nestuser
    - DB_PASSWORD=nestpass
    - DB_NAME=nestdb
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - ELASTICSEARCH_HOST=http://elasticsearch:9200
  depends_on:
    - redis
    - postgres
    - elasticsearch
  volumes:
    - .:/app
  command: yarn start:dev

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    restart: always

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    restart: always

volumes:
  pg_data:
  es_data:
